### PR TITLE
:sparkles: crd: allow specifying spec.preserveUnknownFields

### LINKED ISSUE #476: preserveUnknownFields=false doesn't work with crdVersions=v1
`crdVersions=v1` which is the new default, doesn't work in conjunction with `preserveUnknownFields=false`. The `spec.preserveUnknownFields` simply doesn't appear in the crd. There is an [integration test](https://github.com/kubernetes-sigs/controller-tools/pull/365/files#diff-0ab3d8fb1161ec6dd0c0bfde3d82db95R153-R163) for `v1beta1`, but not for `v1`.

I'm running the following command in a kubebuilder repo:
```
controller-gen "crd:preserveUnknownFields=false,crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```

I'm using defaults in my schema and if applying to a `1.16.13-gke.1` cluster, I get:
```
The CustomResourceDefinition "foo.example.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```
If I add spec.preserveUnknownFields manually to the crd it works

My workaround in the makefile right now is
```
yq w -i config/crd/bases/cluster.paas.getcruise.com_clusters.yaml spec.preserveUnknownFields false
```

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Reinstate crd:preserveUnknownFields option removed by #607 to allow specifying the value of deprecated spec.preserveUnknownFields CRD field.

This is useful for updating CRDs that were automatically converted from v1beta1 version which had true as a default value and resulted in:
```
$ kubectl get crd foo.bar -o yaml | grep preserveUnknownFields
  preserveUnknownFields: true
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
```

For #476

### CODE REVIEW

File: pkg/crd/gen_integration_test.go [hunk 1]
```diff
@@ -119,6 +119,32 @@ var _ = Describe("CRD Generation proper defaulting", func() {
 		expectedOut := string(expectedFileFoos) + string(expectedFileZoos)
 		Expect(out.buf.String()).To(Equal(expectedOut), cmp.Diff(out.buf.String(), expectedOut))
 	})
+
+	It("should add preserveUnknownFields=false when specified", func() {
```
Comment (sbueringer) [inline pkg/crd/gen_integration_test.go:123]: Let's also add a case that it doesn't show up with false if PreserveUnknownFields is nil

**Review by sbueringer — COMMENTED** [review]
Makes sense to me as the alternative seems to be that users have to modify the CRD objects manually

File: pkg/crd/gen_integration_test.go (hunk 1 above)
Comment (AlexanderYastrebov) [reply pkg/crd/gen_integration_test.go:123]: Added

**Comment by sbueringer** [comment]
Thx!

/ok-to-test

/lgtm

Let's see if someone else has an opinion on it

(cc @vincepri @alvaroaleman )

File: pkg/crd/gen_integration_test.go [hunk 2]
```diff
@@ -119,6 +119,43 @@ var _ = Describe("CRD Generation proper defaulting", func() {
...
+		By("searching preserveUnknownFields")
+		Expect(out.buf.String()).To(ContainSubstring("preserveUnknownFields: false"))
+	})
+
+	It("should add preserveUnknownFields=true when specified", func() {
+		By("calling Generate")
+		yes := true
+		gen := &crd.Generator{
+			CRDVersions:           []string{"v1"},
+			PreserveUnknownFields: &yes,
```
Comment (vincepri) [inline pkg/crd/gen_integration_test.go:141]: Shouldn't we disallow adding true for v1?

Comment (sbueringer) [reply pkg/crd/gen_integration_test.go:141]: As we don't support generating v1beta1 CRDs anymore, I think it's as easy as "always" disallowing true

Comment (AlexanderYastrebov) [reply pkg/crd/gen_integration_test.go:141]: Is it really necessary? API server does not allow `preserveUnknownFields: true` anyway:
```console
kubectl apply -f pkg/crd/testdata/gen/bar.example.com_foos.yaml
The CustomResourceDefinition "foos.bar.example.com" is invalid: 
* spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
* spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-kubernetes-preserve-unknown-fields to true in spec.versions[*].schema instead
```

Comment (AlexanderYastrebov) [reply pkg/crd/gen_integration_test.go:141]: I think we could let user specify `true` even though it is not supported but I added a check that prohibits that as suggested.

Comment (sbueringer) [reply pkg/crd/gen_integration_test.go:141]: I prefer that we block generation of invalid CRD YAML like in this case. The earlier it fails the better (CRD generation instead of CRD deployment)

**Comment by sbueringer** [comment]
Thx!

/lgtm

/assign @vincepri

File: pkg/crd/gen_integration_test.go (hunk 2 above)
Comment (alvaroaleman) [reply pkg/crd/gen_integration_test.go:141]: @sbueringer it is only invalid if you create the CRD as v1. If it was originally created as v1beta1, then it is valid.

Comment (sbueringer) [reply pkg/crd/gen_integration_test.go:141]: You can still deploy a v1 CRD with the field set to true if the CRD was before created with v1beta1?

Comment (alvaroaleman) [reply pkg/crd/gen_integration_test.go:141]: > You can still deploy a v1 CRD with the field set to true if the CRD was before created with v1beta1?

Yes

Comment (AlexanderYastrebov) [reply pkg/crd/gen_integration_test.go:141]: Let me know if I should remove the check to allow `true` value.

File: pkg/crd/gen.go [hunk 3]
```diff
@@ -85,6 +85,13 @@ type Generator struct {
 
 	// Year specifies the year to substitute for " YEAR" in the header file.
 	Year string `marker:",optional"`
+
+	// PreserveUnknownFields indicates whether or not we should turn off pruning.
+	//
+	// Specifies spec.preserveUnknownFields value that is false and omitted by default.
+	//
+	// It's required to be false for v1 CRDs.
+	PreserveUnknownFields *bool `marker:",optional"`
```
Comment (vincepri) [inline pkg/crd/gen.go:94]:
```suggestion
	// DeprecatedV1beta1CompatibilityPreserveUnknownFields indicates whether 
	// or not we should turn off field pruning for this resource.
	//
	// Specifies spec.preserveUnknownFields value that is false and omitted by default.
	// This value can only be specified for CustomResourceDefinitions that were created with
	// `apiextensions.k8s.io/v1beta1`.
	//
	// The field can be set for compatiblity reasons, although strongly discouraged, resource
	// authors should move to a structural OpenAPI schema instead.
	//
	// See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning 
	// for more information about field pruning and v1beta1 resources compatibility.
	DeprecatedV1beta1CompatibilityPreserveUnknownFields *bool `marker:",optional"`
```

Something like that?

File: pkg/crd/gen_integration_test.go (hunk 2 above)
Comment (vincepri) [reply pkg/crd/gen_integration_test.go:141]: Added a suggestion above to rename the exposed field and prevent possible footguns

Comment (sbueringer) [reply pkg/crd/gen_integration_test.go:141]: > Let me know if I should remove the check to allow true value.

Yup, we should allow true. Sorry I thought that v1 CRDs cannot be deployed with true

File: pkg/crd/gen.go (hunk 3 above)
Comment (AlexanderYastrebov) [reply pkg/crd/gen.go:94]: Is this necessary? By default the marker is not used, it will be used by those who solve specific problem and know what they want.

File: pkg/crd/gen_integration_test.go (hunk 2 above)
Comment (AlexanderYastrebov) [reply pkg/crd/gen_integration_test.go:141]: Removed the check to allow `true`.

File: pkg/crd/gen.go (hunk 3 above)
Comment (AlexanderYastrebov) [reply pkg/crd/gen.go]: The link is useful as well as different name from previously existing marker, fixed.
