### PR TITLE
:sparkles: Cross-module support for filesystem paths

### LINKED ISSUE #516: controller-gen crd generation does not work across modules layouts
The operator-sdk [documentation](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart) lays out an operator go project with `api` in the root directory. It also creates a Makefile with the rule `make manifests` defined as
```
$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```
so relying on controller-gen for generation of the operator CRDs.

While migrating an operator [project](https://github.com/apache/camel-k) to using this CRD generation, there exists an issue with apis that have been modularized, ie. api directory with their own mod.go file.

I've created a [repository](https://github.com/phantomjinx/memcached-operator/tree/master) demonstrating the problem using the memcached-operator example.
- An [api](https://github.com/phantomjinx/memcached-operator/tree/master/api/v1) is generated with a version "v1" and given the kind "memcached";
- A 2nd [api](https://github.com/phantomjinx/memcached-operator/tree/master/api/v1alpha1) is generated with a version "v1alpha1" and given the kind "memcachedext";
- The 2nd api then uses a [type](https://github.com/phantomjinx/memcached-operator/blob/master/api/v1alpha1/memcachedext_types.go#L50) from the v1 api hence placing a parent-child dependency on these apis.

For this to compile correctly, the v1 package had to be imported into the v1alpha1 api. This happened to require the api be [modularized](https://github.com/phantomjinx/memcached-operator/blob/master/api/go.mod). Maybe, this is unnecessary for solving the import problem but is required anyway for making available the api as a module in its own right.

Issues:
- `make manifests` fails to generate any CRDs due to the `controller-gen` command;
- If the go.mod is removed then things do get generated and this seems to be a possible workaround. However, a further problem emerges due to v1alpha1 depending on v1 with the v1 CRD containing a duplicated schema, ie. 2 versions of schema v1.

### PR DESCRIPTION
**Pull request by akutz**
This patch updates the controller-gen package loader to support loading packages across Go module boundaries.

This fixes #516 and enables https://github.com/vmware-tanzu/tanzu-framework/pull/2222. Without this PR the CRDs generated from the referenced PR would be missing the types from that project's `./apis/run/v1alpha3` directory as it is a distinct Go module, whereas its siblings, `v1alpha1` and `v1alpha2` belong to the root module (please see the aforementioned PR as to why this is).

_This_ patch has been tested by building the branch from https://github.com/vmware-tanzu/tanzu-framework/pull/2222.

This patch updates the controller-gen package loader to support loading packages across Go module boundaries for filesystem paths. What does this actually mean? Imagine a project with the following structure:

```
my-project/
|
|-- go.mod
|-- go.sum
|
|-- apis/
    |
    |-- v1alpha1/
        |
        |-- go.mod
        |-- go.sum
```

Prior to this patch, the following command, executed from the root of `my-project`, would *not* include the package `my-project/apis/v1alpha1`:

```
controller-gen crd \
  paths=./apis/... \
  crd:trivialVersions=true \
  output:crd:dir=./config/crd/bases
```

The reason the above command would not parse the types from the package `my-project/apis/v1alpha1` is because it is a distinct Go module from the root module, where the command was executed. In fact, while the above command would silently fail to include those types, the following command will fail with an error:

```
controller-gen crd \
  paths=./apis/v1alpha1 \
  crd:trivialVersions=true \
  output:crd:dir=./config/crd/bases
```

The above command fails because the underlying logic to load packages cannot load a path from one package when executed from the working directory of another package.

With this patch, it is now possible for the first command to successfully traverse Go module boundaries for roots that are filesystem paths ending with `...` with the following, high-level logic:

1. If no roots are provided then load the working directory and return early.
1. Otherwise sort the provided roots into two, distinct buckets:
    1. package/module names
    1. filesystem paths

    A filesystem path is distinguished from a Go package/module name by the same rules as followed by the "go" command. At a high level, a root is a filesystem path IFF it meets ANY of the following criteria:

    * is absolute
    * begins with `.`
    * begins with `..`

    For more information please refer to the output of the command `go help packages`.

1. Load the package/module roots as a single call to `packages.Load`. If there are no filesystem path roots then return early.
1. For filesystem path roots ending with `...`, check to see if its descendants include any nested, Go modules. If so, add the directory that contains the nested Go module to the filesystem path roots.
1. Load the filesystem path roots and return the load packages for the package/module roots AND the filesystem path roots.

### CODE REVIEW

**Comment by akutz** [comment]
I force pushed a few updates to documentation to make the code easier to read.

**Comment by akutz** [comment]
I just repushed to add some unit tests to `pkg/loader.LoadRoots` to ensure nothing unintended is being introduced.

**Comment by akutz** [comment]
I added additional assertions to the tests.

**Comment by lubronzhan** [comment]
Hi @droot @alvaroaleman @pwittrock could you help take a look? This is very useful to unblock us.

File: pkg/loader/loader.go [hunk 1]
```diff
@@ -341,13 +343,87 @@ func LoadRootsWithConfig(cfg *packages.Config, roots ...string) ([]*Package, err
...
+		if !d.IsDir() && path.Base(p) == "go.mod" {
+			absPathDirOfGoMod, err := filepath.Abs(filepath.Dir(p))
+			if err != nil {
+				return err
+			}
+			goModDirs = append(goModDirs, absPathDirOfGoMod)
+		}
+		return nil
+	}
+	for i, r := range roots {
```
Comment (alvaroaleman) [inline pkg/loader/loader.go:361]: What is the reason for the new four dot notation? Why would someone ever want to use this recursively but not for submodules, if any?

File: pkg/loader/loader.go [hunk 2]
```diff
@@ -341,13 +343,87 @@ func LoadRootsWithConfig(cfg *packages.Config, roots ...string) ([]*Package, err
...
+		}
+	}
+
+	// loadRoots parses the provided file paths and returns their load packages
+	//
+	// uniqueRoots is used to keep track of the discovered packages to be nice
+	// and try and prevent packages from showing up twice when nested module
+	// support is enabled. there is not harm that comes from this per se, but
+	// it makes testing easier when a known number of modules can be asserted
+	uniqueRoots := map[string]struct{}{}
```
Comment (alvaroaleman) [inline pkg/loader/loader.go:381]: Nit: sets.String makes this more readable

File: pkg/loader/loader.go [hunk 3]
```diff
@@ -329,7 +331,7 @@ func LoadRoots(roots ...string) ([]*Package, error) {
 //
 // This is generally only useful for use in testing when you need to modify
 // loading settings to load from a fake location.
-func LoadRootsWithConfig(cfg *packages.Config, roots ...string) ([]*Package, error) {
+func LoadRootsWithConfig(cfg *packages.Config, roots ...string) (pkgs []*Package, retErr error) {
```
Comment (alvaroaleman) [inline pkg/loader/loader.go:334]: Just to summarize what we do now:
* If four dot notation, traverse and find go.mod files. If found, add to goModDirs
* Load as we already do today
* Iterate go.mod dirs, chdir into them, load ./...
* chdir back to not cause weirdness
Is that dorrect?

File: pkg/loader/loader.go [hunk 4]
```diff
@@ -341,13 +343,87 @@ func LoadRootsWithConfig(cfg *packages.Config, roots ...string) ([]*Package, err
...
+	}
+
+	// load the packages from the main module
+	if err := loadRoots(roots...); err != nil {
 		return nil, err
 	}
 
-	for _, rawPkg := range rawPkgs {
-		l.Roots = append(l.Roots, l.packageFor(rawPkg))
+	if len(goModDirs) > 0 {
```
Comment (alvaroaleman) [inline pkg/loader/loader.go:402]: Nit: Avoid arrowcode through early return, i.E.
```suggestion
	if len(goModDirs) == 0 { return l.roots, nil}
	// submodule handling
```

File: pkg/loader/testmods/childDirB/go.mod [hunk 5]
```diff
@@ -0,0 +1,3 @@
+module sigs.k8s.io/controller-tools/pkg/loader/testmods/childDirB
```
Comment (alvaroaleman) [inline pkg/loader/testmods/childDirB/go.mod:1]: Readability nit, can we rename the submodules to s/dir/submodule, i.E. here childSubmoduleB?

**Review by alvaroaleman — COMMENTED** [review]
Couple if nits. If at all possible I'd like to avoid a new "I really really want to recurse, even across module boundaries" notation and stick with the existing one for that

File: pkg/loader/loader.go (hunk 1 above)
Comment (akutz) [reply pkg/loader/loader.go:361]: The reasoning is to preserve the existing behavior by default. The four-dots enforces an explicit choice to recurse across the boundary.

File: pkg/loader/loader.go (hunk 2 above)
Comment (akutz) [reply pkg/loader/loader.go:381]: Well if I had known that existed... 😄

File: pkg/loader/loader.go (hunk 3 above)
Comment (akutz) [reply pkg/loader/loader.go:334]: You nailed it.

File: pkg/loader/loader.go (hunk 4 above)
Comment (akutz) [reply pkg/loader/loader.go:402]: I was not sure what the repository's preference was. I return early in shorter functions but tend to avoid it in longer ones if possible. But I'm happy to follow the project convention.

File: pkg/loader/testmods/childDirB/go.mod (hunk 5 above)
Comment (akutz) [reply pkg/loader/testmods/childDirB/go.mod:1]: Oh, sure. Makes total sense.

Comment (akutz) [reply pkg/loader/testmods/childDirB/go.mod:1]: Actually, wouldn't that be slightly confusing it the mod name isn't consistent with the file structure? And while I could rename the dir names, that leaves the dir names that *aren't* modules...

File: pkg/loader/loader.go (hunk 4 above)
Comment (akutz) [reply pkg/loader/loader.go]: Resolved with latest push.

File: pkg/loader/testmods/childDirB/go.mod (hunk 5 above)
Comment (alvaroaleman) [reply pkg/loader/testmods/childDirB/go.mod:1]: right but the dirs that aren't modules are just dirs so that should be fine?

Comment (akutz) [reply pkg/loader/testmods/childDirB/go.mod:1]: So you'd have `submodA` and `childdirB`?

File: pkg/loader/loader.go (hunk 1 above)
Comment (alvaroaleman) [reply pkg/loader/loader.go:362]: Well sure, but we can break compatibility and if it improves things we should. So then the question becomes which of the two (including submodules or not) do we consider to be more common? That should be the default.

I think it makes a lot of sense to put api packages into a submodule, so I would assume that to be 80% case and not the other way round. So if anything we should probably add a flag to opt out of this (but it might be ok to wait with that until someone actually complains, because until we don't know if anyone even needs this)

Comment (akutz) [reply pkg/loader/loader.go:362]: So one reason I opted to not make this a flag on the CLI was because I was perhaps a little too fond of the "adding an extra dot." I'm not opposed to the opt-out approach, but it _would_ mean that we cannot just start with the four-dot notation and move to opt-out later. Because then we'd break the people that used four-dots (if it was removed).

I suppose I'd like someone else to break the "tie" as it were, but as I've seen mentioned, this is a project whose  consumption far outweighs its developer engagement.

File: pkg/loader/testmods/childDirB/go.mod (hunk 5 above)
Comment (alvaroaleman) [reply pkg/loader/testmods/childDirB/go.mod:1]: yeah, exactly

Comment (akutz) [reply pkg/loader/testmods/childDirB/go.mod:1]: I mean, my eye might twitch at the inconsistency, but I can live with it 😃

File: pkg/loader/loader.go (hunk 1 above)
Comment (akutz) [reply pkg/loader/loader.go:362]: I guess I'm in this odd predicament of fighting against my own change 😃 I feel somewhat strongly we should not break things, but if you are okay with it, I am too. My one other concern would be what documentation we need to update and where?

Comment (timothysc) [reply pkg/loader/loader.go:362]: Do we have examples of where things would break?  If so... preserve.  Otherwise, change the default and add release notes on the change.

Comment (akutz) [reply pkg/loader/loader.go:362]: I do not, no. Only if people were using Go modules to "hide" certain APIs from this tool. I agree with @alvaroaleman that 80% of people would be fine, and in fact I've been one of the loudest that API dirs _should_ be distinct modules. I just like to err on the side of "don't go breakin' stuff when you don't have to." Then again, I guess I forgot the second part of "move fast..."

Comment (alvaroaleman) [reply pkg/loader/loader.go:362]: IMHO it should also be mentioned that if someone for some reason has a submodule within an api directoty that they do indeed not want to include, they can get that by explicitly including all other dirs in their api dir except the one with the submodule - Yes, that takes a non-zero amount of work but it also makes it way more obvious that that submodule shouldn't be included than abusing a bug to get that behavior

**Comment by akutz** [comment]
/hold

I realized this PR has a bug. Well, the bug is already present, but since this PR claims to add support for cross-module discovery, I feel this PR cannot claim to do so and not address this.

Basically if there's a project with a root Go module and `controller-gen paths=./submod` is used, where `./submod` _is_ a sub-module, then this would fail because the loader will return an error that the path`./submod` is not a member of the root module. 

That is obviously not desirable. Let me think on how to address this.

**Comment by akutz** [comment]
/hold remove

Okay, the issue I discovered should be fixed, and all other comments should be resolved. A few, general comments:

* several tests were updated, and I documented those changes as thoroughly as possible, along with a few TODOs
* one such TODO that occurred a couple of times -- _does the `controller-gen paths=` flag support Go import paths? Because there were at least two, distinct locations in tests that expected that to work. Except this behavior:
  * was not documented as supported anywhere
  * was documented as contrary to that in fact
  * and makes no sense since the loader is designed to translate a file path _into_ the package

  I think we should keep the changes, but I did want to call them out.

@alvaroaleman, please go ahead and take another look when you get a chance. Thank you!

**Comment by akutz** [comment]
/hold cancel

(I don't know why I thought `/hold remove` would work -- I guess it's been too long since I've used one...)

File: pkg/deepcopy/deepcopy_integration_test.go [hunk 6]
```diff
@@ -86,9 +86,30 @@ var _ = Describe("CRD Generation From Parsing to CustomResourceDefinition", func
 		Expect(err).NotTo(HaveOccurred())
 		rt.OutputRules = genall.OutputRules{Default: output}
 
+		// TODO(akutz) This did not used to be necessary for some reason, as it
+		//             seems pkg/loader used to auto-magically act against the
+		//             working directory, even if not roots were specified. this
+		//             behavior is not documented anywhere, and I was torn as to
+		//             put the commented-out code *here* or update the loader to
+		//             assume roots=["."] if len(roots) == 0. For the sake of
+		//             backwards-compatibility I opted for the latter.
```
Comment (alvaroaleman) [inline pkg/deepcopy/deepcopy_integration_test.go:95]: I think defaulting to `.` when unset makes sense (and changing that might break ppl).

Edit: Now I read the other comment, so this never worked when using the `cli`?

File: pkg/loader/loader.go [hunk 7]
```diff
@@ -341,13 +343,164 @@ func LoadRootsWithConfig(cfg *packages.Config, roots ...string) ([]*Package, err
...
+		r := filepath.Clean(r)
+
+		// get the absolute path of the root
+		if !filepath.IsAbs(r) {
+
+			// if the initial value of cfg.Dir was non-empty then use it when
+			// building the absolute path to this root. otherwise use the
+			// filepath.Abs function to get the absolute path of the root based
+			// on the working directory
+			if cfgDir != "" {
```
Comment (alvaroaleman) [inline pkg/loader/loader.go:433]: so cfgDir might not be $PWD?

**Comment by akutz** [comment]
FWIW, here's my hot take -- let's kill two bird here:

1. Default to the current path if no roots are specified
2. Update both affected tests to _not_ specify any roots at all, meaning their current directory, the temp one, will be used.

It addresses all three test changes in one, fell swoop.

File: pkg/crd/schema_test.go [hunk 8]
```diff
@@ -46,7 +46,16 @@ func transform(t *testing.T, expr string) *apiext.JSONSchemaProps {
 		},
 	}
 
-	pkgs, exported, err := testloader.LoadFakeRoots(pkgstest.Modules, modules, moduleName)
+	// TODO(akutz) the root specified is the current directory instead of the
```
Comment (alvaroaleman) [inline pkg/crd/schema_test.go:49]: But using an import path would have worked? I am slightly worried that if yes and we change that, we might break ppl

File: pkg/loader/loader.go (hunk 7 above)
Comment (akutz) [reply pkg/loader/loader.go:433]: Yep. See the public `LoadRoots` function, it just constructs an empty `Config` -- https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/pkg/loader/loader.go#L316-L324. 

The `LoadRootsWithConfig` is event documented as _for testing_ -- https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/pkg/loader/loader.go#L326-L332

It was only set explicitly in the past from a test that used it with a temp directory. I switched to using it from `os.Chdir` as it better supports parallel testing. 

FWIW, it is eventually set to `os.Getwd` if still empty by the time it reaches https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.10:go/packages/packages.go;l=563

File: pkg/deepcopy/deepcopy_integration_test.go (hunk 6 above)
Comment (akutz) [reply pkg/deepcopy/deepcopy_integration_test.go:95]: It was not documented as such, no. The flag is not omitted from any example:

```bash
	# Generate RBAC manifests and crds for all types under apis/,
	# outputting crds to /tmp/crds and everything else to stdout
	controller-gen rbac:roleName=<role name> crd paths=./apis/... output:crd:dir=/tmp/crds output:stdout

	# Generate deepcopy/runtime.Object implementations for a particular file
	controller-gen object paths=./apis/v1beta1/some_types.go

	# Generate OpenAPI v3 schemas for API packages and merge them into existing CRD manifests
	controller-gen schemapatch:manifests=./manifests output:dir=./manifests paths=./pkg/apis/... 

	# Run all the generators for a given project
	controller-gen paths=./apis/...
```

or shown as optional in help:

```bash
+paths package
	=<[]string>  represents paths and go-style path patterns to use as package roots.
```

I've traced out how the paths are ingested, and they do allow them to be empty since they're not a proper flag. They come this way:

1. the command line options are parsed from https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/cmd/controller-gen/main.go#L168
2. which creates a set of proto, runtime options at https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/pkg/genall/options.go#L76
3. which parses the command line `paths` optoin at https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/pkg/genall/options.go#L149
4. which get returned and read into the `ForRoots` function at https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/pkg/genall/options.go#L82
5. which is what calls `loader.LoadRoots` at https://github.com/kubernetes-sigs/controller-tools/blob/cb13ac551a0599044e50ed756735a8f438a24631/pkg/genall/genall.go#L211

File: pkg/crd/schema_test.go (hunk 8 above)
Comment (akutz) [reply pkg/crd/schema_test.go:49]: Yes, it would have, but it was never documented as such. It will definitely break people relying on that, but I thought you were fine with that as long as we release note the change?

Comment (akutz) [reply pkg/crd/schema_test.go:49]: Ultimately the default behavior could be preserved by handling roots and following the logic of `go list` by adhering to the guidance from:

```
$ go help packages
Many commands apply to a set of packages:

	go action [packages]

Usually, [packages] is a list of import paths.

An import path that is a rooted path or that begins with
a . or .. element is interpreted as a file system path and
denotes the package in that directory.

Otherwise, the import path P denotes the package found in
the directory DIR/src/P for some DIR listed in the GOPATH
environment variable (For more details see: 'go help gopath').

If no import paths are given, the action applies to the
package in the current directory.

There are four reserved names for paths that should not be used
for packages to be built with the go tool:

- "main" denotes the top-level package in a stand-alone executable.

- "all" expands to all packages found in all the GOPATH
trees. For example, 'go list all' lists all the packages on the local
system. When using modules, "all" expands to all packages in
the main module and their dependencies, including dependencies
needed by tests of any of those.

- "std" is like all but expands to just the packages in the standard
Go library.

- "cmd" expands to the Go repository's commands and their
internal libraries.

Import paths beginning with "cmd/" only match source code in
the Go repository.

An import path is a pattern if it includes one or more "..." wildcards,
each of which can match any string, including the empty string and
strings containing slashes. Such a pattern expands to all package
directories found in the GOPATH trees with names matching the
patterns.

To make common patterns more convenient, there are two special cases.
First, /... at the end of the pattern can match an empty string,
so that net/... matches both net and packages in its subdirectories, like net/http.
Second, any slash-separated pattern element containing a wildcard never
participates in a match of the "vendor" element in the path of a vendored
package, so that ./... does not match packages in subdirectories of
./vendor or ./mycode/vendor, but ./vendor/... and ./mycode/vendor/... do.
Note, however, that a directory named vendor that itself contains code
is not a vendored package: cmd/vendor would be a command named vendor,
and the pattern cmd/... matches it.
See golang.org/s/go15vendor for more about vendoring.

An import path can also name a package to be downloaded from
a remote repository. Run 'go help importpath' for details.

Every package in a program must have a unique import path.
By convention, this is arranged by starting each path with a
unique prefix that belongs to you. For example, paths used
internally at Google all begin with 'google', and paths
denoting remote repositories begin with the path to the code,
such as 'github.com/user/repo'.

Packages in a program need not have unique package names,
but there are two reserved package names with special meaning.
The name main indicates a command, not a library.
Commands are built into binaries and cannot be imported.
The name documentation indicates documentation for
a non-Go program in the directory. Files in package documentation
are ignored by the go command.

As a special case, if the package list is a list of .go files from a
single directory, the command is applied to a single synthesized
package made up of exactly those files, ignoring any build constraints
in those files and ignoring any other files in the directory.

Directory and file names that begin with "." or "_" are ignored
by the go tool, as are directories named "testdata".
```

Comment (akutz) [reply pkg/crd/schema_test.go:49]: For transparency, it's also possible for the package driver to be overridden to be an external driver via https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.10:go/packages/external.go;drc=refs%2Ftags%2Fv0.1.10;l=49. If we adopted the above logic, it could still fail if someone ran `GOPACKAGESDRIVER=/usr/local/bin/my-pkg-driver controller-gen crd ...`.

**Comment by akutz** [comment]
@alvaroaleman and I speaking on Slack. A few notes:

* we're discussing this thread -- https://github.com/kubernetes-sigs/controller-tools/pull/663#discussion_r863203697
* a work-around was discovered!

    ```diff
    manifests: tools ## Generate manifests e.g. CRD, RBAC etc.
     	$(CONTROLLER_GEN) \
     		$(CRD_OPTIONS) \
    -		paths=./apis/... \
    +		paths='./apis/...;github.com/vmware-tanzu/tanzu-framework/apis/cni/...;github.com/vmware-tanzu/tanzu-    framework/apis/cpi/...' \
     		output:crd:artifacts:config=config/crd/bases
    ```

    If the full module name, even with the traversal pattern, is used in a project with nested sub-modules, and the root module has the appropriate `replace` directives, everything works as expected. I verified this with the original tanzu-framework PR. I'm going to be updating _that_ PR to use this work-around for now.

Both @alvaroaleman and I think _this_ PR still has value as the aforementioned work-around is unintuitive, so I'll keep cracking on this by updating the loader to follow the logic from `go help packages` in identifying what is a filesystem path and what is a package/module name.

**Comment by akutz** [comment]
Okay, now the prior behavior (support no paths, support package/module names directly, basically anything you can do with `go list`) is now supported as well.

The one thing not yet supported is cross-module support when explicitly specifying a package name ending with `/...`. Cross-module support only works for local filesystems.

**Review by alvaroaleman — APPROVED** [review]
thanks!

**Comment by akutz** [comment]
/hold

I'm going to update it with a slight optimization.

**Comment by akutz** [comment]
/hold cancel

Okay, removing the hold, and I will update the PR description as well. I added a bunch of documentation and some optimizations.

**Review by alvaroaleman — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
For visibility, looks like this PR introduced this issue: https://github.com/kubernetes-sigs/controller-tools/issues/680

**Comment by mmingdai** [comment]
For visibility, this PR also introduced https://github.com/kubernetes-sigs/controller-tools/issues/837
