### PR TITLE
🐛 Fix implicit aliasing issue in nested maps

### LINKED ISSUE #809: Nested maps deepcopy results in - Implicit memory aliasing in for loop - issue
How to reproduce
1) Create a field of type map[string]map[string]string  in an API resource
2) Generate Deepopy using controller-gen
results in following code
```
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
```

This throws the following error while running [gosec](https://github.com/securego/gosec) tool

```
- G601 (CWE-118): Implicit memory aliasing in for loop. (Confidence: MEDIUM, Severity: MEDIUM)
   1352: 			} else {
  > 1353: 				in, out := &val, &outVal
    1354: 				*out = make(map[string]string, len(*in))
```

### PR DESCRIPTION
**Pull request by shyamradhakrishnan**
Fix #809 

The PR fixes the implicit memory aliasing issue in autogenerated DeepCopy method when the field is a nested map.

### CODE REVIEW

File: pkg/deepcopy/traverse.go [hunk 1]
```diff
@@ -374,7 +374,8 @@ func (c *copyMethodMaker) genMapDeepCopy(actualName *namingInfo, mapType *types.
 				c.IfElse("val == nil", func() {
 					c.Line("(*out)[key] = nil")
 				}, func() {
-					c.Line("in, out := &val, &outVal")
+					c.Line("inVal := (*in)[key]")
+					c.Line("in, out := &inVal, &outVal")
```
Comment (camilamacedo86) [inline pkg/deepcopy/traverse.go:378]: Thank you a lot for the contribution 🥇 
Could you please ensure that the change/issue is also covered with a test?

Comment (shyamradhakrishnan) [reply pkg/deepcopy/traverse.go:378]: Thanks for the review @camilamacedo86 I have added a nested map in cronjob_types.go and that fields and other fields are calling this new line. I hope that will cover as a test case. Can you suggest if I need to add test cases in other places as well?

**Comment by shyamradhakrishnan** [comment]
@vincepri @joelanford @camilamacedo86 gentle reminder for review

**Comment by gilbahat** [comment]
Hi, just ran into this as well. Looks fairly complete to me and 2 months passed, so maybe a gentle nudge is fair by now.

**Comment by shyamradhakrishnan** [comment]
@vincepri @joelanford @camilamacedo86 gentle reminder for review

**Comment by sbueringer** [comment]
Played a bit around with it. Works as expected

/lgtm
/approve
