### PR TITLE
🐛 Fix flattening chains of references to references

### LINKED ISSUE #324: controller-tools creates schema with '$ref' which is not supported in k8s
```golang
type Bar struct{
	A string `json:"a"`
}

// Foo is a Bar
type Foo Bar

type CronJobSpec struct {
	Foo Foo `json:"foo"`
}
```

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: cronjobs.batch.tutorial.kubebuilder.io
spec:
  group: batch.tutorial.kubebuilder.io
  names:
    kind: CronJob
    listKind: CronJobList
    plural: cronjobs
    singular: cronjob
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CronJob is the Schema for the cronjobs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CronJobSpec defines the desired state of CronJob CronJobSpec
            defines the desired state of CronJob
          properties:
            foo:
              $ref: '#/definitions/Bar'
              description: Foo is a Bar
          required:
          - foo
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

`kubectl apply` returns a `$ref: Forbidden: $ref is not supported`

/kind bug

### PR DESCRIPTION
**Pull request by skaslev**
Without this change running controller-gen on Knative's APIs
results in unexpanded reference for the Conditions[1] type in
the generated OpenAPI schema:

    conditions:
      $ref: '#/definitions/knative.dev~1pkg~1apis~0Conditions'

After this change Conditions gets properly flattened and no references
are present in the resulting schema.

Fixes #324

[1] https://github.com/knative/pkg/blob/ce05a3de31ed80e98862a0ea024977097fd0e4a5/apis/duck/v1/status_types.go#L34

### CODE REVIEW

File: pkg/crd/schema_visitor.go [hunk 1]
```diff
@@ -48,11 +48,18 @@ type schemaWalker struct {
...
 func (w schemaWalker) walkSchema(schema *apiext.JSONSchemaProps) {
-	subVisitor := w.visitor.Visit(schema)
-	if subVisitor == nil {
-		return
+	// Walk a potential chain of schema references
+	subVisitor := w.visitor
+	for {
+		subVisitor = subVisitor.Visit(schema)
+		if subVisitor == nil {
+			return
```
Comment (DirectXMan12) [inline pkg/crd/schema_visitor.go:56]: can you add a test for this?

Make sure to have one for circular references too

Comment (skaslev) [reply pkg/crd/schema_visitor.go:60]: Added a test that on current master produces

```
    typeRefChain:
      $ref: '#/definitions/testdata.kubebuilder.io~1cronjob~1api~0Integer'
```

but works correctly with this PR.

Also added cycle detection logic so that this `for` terminates for circular references.
I couldn't come up with circular test that would compile though.

**Comment by skaslev** [comment]
@DirectXMan12 Thank you for the review. 

Can you take another look?

File: pkg/crd/schema_visitor.go (hunk 1 above)
Comment (skaslev) [reply pkg/crd/schema_visitor.go:60]: Found a simpler reproducer from #324 and switched to using it instead.

**Comment by DirectXMan12** [comment]
pushed an extra test, plus a test for circular references

/lgtm
/approve

**Comment by skaslev** [comment]
Thanks for doing this. Seems that it didn't land because of a misspelling in the test:

```
pkg/crd/flatten_type_test.go:112:35: `ciruclar` is a misspelling of `circular` (misspell)
		It("should not infinite-loop on ciruclar references", func() {
```

**Comment by DirectXMan12** [comment]
gah, thanks for fixing the typo

/lgtm
