### PR TITLE
:bug: Smarter allOf flattening/validation preservation

### LINKED ISSUE #217: flattening wipes out field validation on type aliases
Flattening causes type alias information to override field information, which currently wipes any field specific validation.  We'll want to fix this, but we'll need to somehow merge the two sets of validation.

In case of disjoint sets of validation types this is easy.  In case of overlap (e.g. two pattern fields, two enums, etc), it's a bit more unclear what to do.  The "most correct" would probably be to use `allOf`, but that's non-structural.

@sttts

### PR DESCRIPTION
**Pull request by DirectXMan12**
This improves our allOf flattening so that it progressively works up the
chain, pushing allOf down until it's no longer needed, or it's at the
most specific point.  Along the way, if two allOfs would be identical,
they'll be merged.

We then make use of this by converting our ref merger to just stick
both halves in an allOf, and then let the allOf flattener deal with it.

The previous behavior of flattening simple allOfs (like the ones to
embedded references) just "fall out" of the new logic.

In simple (non-overlapping) cases, we still end up with the
simplest-looking validation, and in complex cases, we're able to
preserve "structurality" (see the structure schema) KEP by dealing with
those fields explicitly when we need to.  However, just letting the
flattener do its thing often solves the issue.

Fixes #217

### CODE REVIEW

**Comment by DirectXMan12** [comment]
We *really* need tests for this.  Might try to get to them tomorrow, but wanted to get this up for review in the mean time.

@sttts can you sanity check the behavior here?

File: pkg/crd/flatten.go [hunk 1]
```diff
@@ -26,47 +27,176 @@ import (
...
+// pkg/loader.Package that we need to record errors in places were it might not
+// make sense to have a loader.Package
+type ErrorRecorder interface {
+	// AddError records that the given error occurred.
+	// See the documentation on loader.Package.AddError for more information.
+	AddError(error)
+}
+
+// isOrNil checks if val is nil if val is of a nillable type, otherwise,
+// it comparse val to valuInt (which should probably be the zero value).
```
Comment (sttts) [inline pkg/crd/flatten.go]: nit: valInt

File: pkg/crd/flatten.go [hunk 2]
```diff
@@ -26,47 +27,176 @@ import (
...
+func isOrNil(val reflect.Value, valInt interface{}, zeroInt interface{}) bool {
```
Comment (sttts) [inline pkg/crd/flatten.go]: why the Int postfix?

Comment (sttts) [reply pkg/crd/flatten.go]: A better name would be isZeroOrNil. But also that is actually wrong: we never compare with zero in case of nillable types.

File: pkg/crd/flatten.go [hunk 3]
```diff
@@ -26,47 +27,176 @@ import (
...
+		return val.IsNil()
+	default:
+		return valInt == zeroInt
+	}
+}
+
 // flattenAllOfInto copies properties from src to dst, then copies the properties
 // of each item in src's allOf to dst's properties as well.
-func flattenAllOfInto(dst *apiext.JSONSchemaProps, src apiext.JSONSchemaProps) {
+func flattenAllOfInto(dst *apiext.JSONSchemaProps, src apiext.JSONSchemaProps, errRec ErrorRecorder) {
```
Comment (sttts) [inline pkg/crd/flatten.go]: why not return an aggregated error? No need for a complex ErrorRecorder construct.

File: pkg/crd/flatten.go (hunk 2 above)
Comment (sttts) [reply pkg/crd/flatten.go]: why not make a `isZero` func? nil is the zero value of nillable types.

File: pkg/crd/flatten.go [hunk 4]
```diff
@@ -26,47 +27,176 @@ import (
...
+		if isOrNil(srcField, srcInt, zeroInt) {
+			// nothing to copy from src, continue
+			continue
+		}
+
+		dstField := dstVal.Field(i)
+		dstInt := dstField.Interface()
+		if isOrNil(dstField, dstInt, zeroInt) {
+			// dst is empty, continue
+			dstField.Set(srcField)
```
Comment (sttts) [inline pkg/crd/flatten.go]: this does not work for nullable.

```
type: array
allOf:
- type: array
   nullable: true
```
is not equivalent to
```
type: array
nullable: true
```
because `null` is valid for the latter, but not for the former.

File: pkg/crd/flatten.go [hunk 5]
```diff
@@ -26,47 +27,176 @@ import (
...
+				errRec.AddError(fmt.Errorf("conflicting types in allOf branches in schema: %s vs %s", dstInt, srcInt))
+			}
+			// keep the destination value, for now
+		// TODO(directxman12): Default -- use field?
+		// TODO(directxman12):
+		// - Dependencies: if field x is present, then either schema validates or all props are present
+		// - AdditionalItems: like AdditionalProperties
+		// - Definitions: common named validation sets that can be references (merge, bail if duplicate)
+		case "AdditionalProperties":
+			// TODO(directxman12): handle the bool too
```
Comment (sttts) [inline pkg/crd/flatten.go]: we don't support `false` if I remember right. `additionalSchema: true` is a no-op logically, but has influence on pruning.

File: pkg/crd/flatten.go [hunk 6]
```diff
@@ -26,47 +27,176 @@ import (
...
+			dstRemVal.Field(i).Set(dstField)
+			// ...and clear the original
+			dstField.Set(zeroVal)
+		}
 	}
-	for _, propName := range src.Required {
-		dst.Required = append(dst.Required, propName)
+
+	if hoisted {
+		dst.AllOf = append(dst.AllOf, dstRemainder, srcRemainder)
```
Comment (sttts) [inline pkg/crd/flatten.go]: this will potentially not return a structural schema. Types, nullable, etc., i.e. everything from https://github.com/kubernetes/kubernetes/blob/9ecc57ef880c475c052e4ab472307202499cf8d9/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/structural.go#L47 has to be pushed into the root. Those cannot be under `allOf`.

File: pkg/crd/flatten.go (hunk 3 above)
Comment (sttts) [inline pkg/crd/flatten.go]: this needs exhaustive tests.

File: pkg/crd/flatten.go (hunk 2 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: there's an issue with comparibility -- I original was just comparing against the zero type, but encountered some issues with non-comparibility -- reflect is a bit weird in this regard, although it's possible I made a mistake.

> why the Int postfix

`Int` is the `interface{}` form, `val` is the `reflect.Value` form.

File: pkg/crd/flatten.go (hunk 3 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: aggregated errors then need to be extracted later, and this is the pattern used almost literally everywhere else in controller-tools, since it allows us to attach better error data in many cases.

File: pkg/crd/flatten.go (hunk 5 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: that's what I thought, but wanted to check with you first.  good to confirm.

File: pkg/crd/flatten.go (hunk 6 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: right -- that's what the above does -- we only `hoist` for properties that aren't listed above, so `type`, `nullable`, etc should be handled there.

File: pkg/crd/flatten.go (hunk 3 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: yes, agreed :-)

File: pkg/crd/flatten.go (hunk 2 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: we can probably get away with just re-calling `Interface` here, though -- it'll be a bit of a performance hit, but it's prob not too big a deal.  Can profile after writing tests.

File: pkg/crd/flatten.go (hunk 4 above)
Comment (sttts) [reply pkg/crd/flatten.go]: I think with structural schemas we are saved here: nullable is not allowed below allOf.

File: pkg/crd/flatten.go (hunk 6 above)
Comment (sttts) [reply pkg/crd/flatten.go]: Towards structural schema, take a look at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/validation.go#L63. You might want to call that somewhere, or even use the Structural type directly.

**Comment by DirectXMan12** [comment]
Added some unit tests around allOf flattening, and and overall integration test of the whole package (give or take) using the cronjob tutorial files.

File: pkg/crd/flatten.go (hunk 4 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: huh?  How does that work?

**Comment by damemi** [comment]
@DirectXMan12 any updates on this? I tested and this fixes the problem I mentioned

**Comment by DirectXMan12** [comment]
hmm... that's a bug

**Comment by DirectXMan12** [comment]
/hold

want a couple more tests

**Comment by DirectXMan12** [comment]
fixed
/unhold

should have more detailed unit tests of the non-allof flattening, but will need to re-jigger things a bit for that, potentially.

**Comment by DirectXMan12** [comment]
In the mean time, the integration test should be sufficient

**Comment by DirectXMan12** [comment]
better unit tests for flattening pushed anyway.  This brings us to pretty decent test coverage overall.

File: pkg/crd/flatten.go (hunk 6 above)
Comment (DirectXMan12) [reply pkg/crd/flatten.go]: let's file a follow-up issue for that.
